name: shell script running inside runner
on: workflow_dispatch
jobs:
   checkout:
     name: checkingout the repository
     runs-on: ubuntu-latest
     steps: 
        - name: checkout the action
          uses : actions/checkout@v6
        - name : executing the permission for shell script
          run : chmod +x run_env.sh
        - name : executing the shell script
          run : sh run_env.sh
