name: artifacts workflow

on:
  workflow_dispatch:

jobs:
  upload:
    name: artifact upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create env file
        run: env > env.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: env_var
          path: env.sh

  download:
    name: artifact download
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: env_var

      - name: Verify downloaded file
        run: |
          ls -l
          cat env.sh
