name: artifacts workflow
on: workflow_dispatch
jobs:
  upload:
     name: artifacts upload
     runs-on: ubuntu-latest
     steps:
        - name: checkout actions
          uses: actions/checkout@v4
        - name: shell script creation action
          run: env  > env.sh
        - name: upoad artifact
          uses: actions/upload-artifact@v4
          with: 
             name: env_var
             path: env.sh
  download:
     name: artifacts download
     runs-on: ubuntu-latest
     needs: upload
     steps:
        - name: download artifact
          uses: actions/download-artifact@v4
          with:
             name: env_var
        - name: viewing the file
          run: |
           ls -lrt
           cat env.sh
