name: First workflow
on: workflow_dispatch
jobs:
   first-job:
      name: interview questions
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - run: |
              echo " Tell me about yourself"
              cat README.md 
   second-job: 
      name: technical interview
      needs: first-job
      runs-on: ubuntu-latest
      steps: 
         - uses: actions/checkout@v4
         - run: sh run_env.sh
   third-job:
       name: finished two jobs
       needs: second-job
       runs-on: ubuntu-latest
       steps: 
         - run: echo "Great, You got selected"
