name: First workflow
on: workflow_dispatch
jobs:
  first-job: 
     name: interview questions
     runs-on: ubuntu-latest
     steps:
        - run: echo " Tell me about yourself"  > int.sh
        - uses: actions/upload-artifact@v4
          with:
             name: interview
             path: int.sh

  second-job:
      name: interview questions
      needs: first-job
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: interview
        - uses: actions/checkout@v4
        - run: |
             ls -lrth
             cat interview
             sh run_env.sh >> int.sh
        - uses: actions/upload-artifact@v4
          with:
             name: interview
             path: int.sh

  third-job:
      name: interview questions
      needs: second-job
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/download-artifact@v4
        - uses: actions/checkout@v4
        - run: |
             cat int.sh
             echo "Succesfully tested the upload and download actions"
