name: First workflow
on: workflow_dispatch
jobs:
   first-job:
      name: interview questions
      runs-on: ubuntu-latest
      steps:
         - name: first question
           run: echo "Tell me about yourself"
         - name: second question
           uses: actions/checkout@v4
         - name: third question
           run:  cat README.md
