name: First workflow
on: workflow_dispatch
jobs:
   first-job:
      name: interview questions
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - run: |
              echo "Tell me about yourself"
              cat README.md   
