name: step and job level timeout
on:
   workflow_dispatch:
      branches:
          - main
          - dev
          - production
jobs:
   job1:
    name: steptimeout
    runs-on: ubuntu-latest
    steps:
        - name: sleep for few seconds
          run: sleep 130
          timeout-minutes: 1
