name: first workflow
on: 
  workflow_dispatch: 
             branch: [main]
jobs:
    build:
      runs-on: ubunutu-latest
      steps:
        - uses: actions/checkout@v4
        - run: |
               chmod +x run_env.sh
               sh run_env.sh
