name: matrix configurations
on:
   workflow_dispatch:
      branches:
          - main
          - dev
          - production
jobs:
  deployment:
     name: matrix deployments
     runs-on: ${{ matrix.os }}
     strategy:
       max-parallel: 2
       fail-fast: false
       matrix:
           os: [windows-latest, ubuntu-latest]
           images: [helloworld, alpine]
           exclude: 
              - os : windows-latest
                images: alpine
           include:
              - os : ubuntu-latest
                images: node:alpine
     steps:
       - name: creating a  ${{ matrix.images }} on ${{ matrix.os }}
         run: docker run ${{ matrix.images }}
